---

- name: Install epel-release
  yum:
    name: epel-release
    state: present

- name: Install nginx
  yum:
    name: "{{ item }}" 
    state: latest
  with_items:
    - nginx
    - rsync 

- name: Install dumb init
  get_url:
    url: https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64
    dest: /usr/bin/dumb-init
    owner: root
    group: root
    mode: 0775

- name: Put nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0664

- name: Ensure run state directory
  file:
    path: /run/nginx
    state: directory
    owner: nginx
    group: root
    mode: 0755

- name: Clean yum cache
  command: yum clean all

